version: "3"
services:
  db:
    build:
      context: ./db
      dockerfile: Dockerfile
    hostname: app
    environment:
      POSTGRES_PASSWORD: postgres
    volumes:
      - "./data:/var/lib/postgresql/data"
    ports:
      - "5433:5432"

  app:
    build:
      context: ./app
      dockerfile: Dockerfile
    environment:
      APP_ENV: prod
    depends_on:
      - db