version: "3"

services:

  db:
    build:
      context: ./db
    container_name: saasestate_geo_db
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: geo
    volumes:
      - ./db/data:/var/lib/postgresql/data
    ports:
      - 5433:5432

  app:
    build:
      context: ./app
    container_name: saasestate_geo_app
    environment:
      APP_ENV: prod
    depends_on:
      - db